


function parseMonthlySheetName_(sheetName) {

  const text =
    String(sheetName || "").trim();


  for (
    let index = 0;
    index < DASHBOARD_CONFIG.MONTHS_RU.length;
    index++
  ) {

    const prefix =
      DASHBOARD_CONFIG.MONTHS_RU[index] +
      " ";


    if (
      text.indexOf(prefix) !== 0
    ) {
      continue;
    }


    const yearText =
      text.slice(prefix.length);


    if (!/^20\d{2}$/.test(yearText)) {
      return null;
    }


    return {
      year: Number(yearText),
      month: index + 1
    };
  }


  return null;
}


function listMonthlySheetDescriptors_(ss) {

  return (ss.getSheets() || [])
    .map(
      function(sheet) {

        const parsed =
          parseMonthlySheetName_(
            sheet.getName()
          );


        return parsed
          ? {
              year: parsed.year,
              month: parsed.month,
              sheetName: sheet.getName(),
              sheet: sheet
            }
          : null;
      }
    )
    .filter(
      function(item) {
        return Boolean(item);
      }
    )
    .sort(
      function(a, b) {
        return (
          a.year - b.year ||
          a.month - b.month
        );
      }
    );
}


function getAutoGeneratedMonthValue_(
  year,
  month
) {

  return (
    String(year) +
    "-" +
    String(month).padStart(2, "0")
  );
}


function markAutoGeneratedMonthlySheet_(
  sheet,
  year,
  month
) {

  const key =
    MONTHLY_SHEET_CREATION_CONFIG
      .AUTO_GENERATED_METADATA_KEY;


  (sheet.getDeveloperMetadata() || [])
    .filter(
      function(item) {
        return item.getKey() === key;
      }
    )
    .forEach(
      function(item) {
        item.remove();
      }
    );


  sheet.addDeveloperMetadata(
    key,
    getAutoGeneratedMonthValue_(
      year,
      month
    )
  );
}


function isAutoGeneratedMonthlySheet_(
  sheet,
  year,
  month
) {

  if (
    !sheet ||
    typeof sheet.getDeveloperMetadata !== "function"
  ) {
    return false;
  }


  const key =
    MONTHLY_SHEET_CREATION_CONFIG
      .AUTO_GENERATED_METADATA_KEY;


  const expected =
    getAutoGeneratedMonthValue_(
      year,
      month
    );


  return (sheet.getDeveloperMetadata() || [])
    .some(
      function(item) {
        return (
          item.getKey() === key &&
          item.getValue() === expected
        );
      }
    );
}


function getMonthlySheetName_(
  year,
  month
) {

  return (
    DASHBOARD_CONFIG.MONTHS_RU[
      month - 1
    ] +
    " " +
    year
  );
}