


function refreshDashboardLinksUnlocked_() {

  const ss =
    SpreadsheetApp.getActiveSpreadsheet();


  const monthlyAnalyses =
    collectMonthlyAnalyses_(ss);


  const carryoverAudit =
    auditMonthlyCarryovers_(
      monthlyAnalyses.carryContextAnalyses ||
      monthlyAnalyses
    );


  if (carryoverAudit.issues.length) {

    Logger.log(
      carryoverAudit.message
    );


    if (
      carryoverAudit.issues.some(
        function(item) {
          return item.autoGenerated;
        }
      )
    ) {
      throw new Error(
        "자동 생성 월의 이월재고가 전월 최종재고와 일치하지 않습니다.\n" +
        carryoverAudit.message
      );
    }
  }


  const dailyRecords =
    collectAnnualDailyKpiRecords_(
      monthlyAnalyses
    );


  const msySummary =
    calculateCumulativeExpectedMsy_(
      dailyRecords
    );


  const latestMonthSummary =
    buildLatestMonthSummary_(
      dailyRecords
    );


  const annualMonthlySummary =
    buildAnnualMonthlySummary_(
      dailyRecords
    );


  refreshMonthlyLinkSheetInternal_(
    ss,
    monthlyAnalyses,
    msySummary,
    latestMonthSummary
  );


  refreshAnnualLinkSheetInternal_(
    ss,
    monthlyAnalyses,
    msySummary,
    annualMonthlySummary
  );
}