


/***************************************************************
 * 실행 1회용 월별 분석 컨텍스트
 ***************************************************************/

// Existing write-enabled callers keep their signature and status updates.
function collectMonthlyAnalyses_(ss, reportingYear) {
  return collectMonthlyAnalysesWithStatusPolicy_(ss, reportingYear, true);
}

// Diagnostics compute the same report without persisting ledger O-column statuses.
function collectMonthlyAnalysesReadOnly_(ss, reportingYear) {
  return collectMonthlyAnalysesWithStatusPolicy_(ss, reportingYear, false);
}

function collectMonthlyAnalysesWithStatusPolicy_(ss, reportingYear, writeStatuses) {

  const year =
    Number(
      reportingYear ||
      getDashboardReportingYear_()
    );


  const descriptors =
    DASHBOARD_CONFIG.MONTHS_RU
      .map(
        function(monthName, index) {

          const sheetName =
            monthName +
            " " +
            year;


          const sheet =
            ss.getSheetByName(
              sheetName
            );


          return sheet
            ? {
                year: year,
                month: index + 1,
                sheetName: sheetName,
                sheet: sheet
              }
            : null;
        }
      )
      .filter(
        function(item) {
          return Boolean(item);
        }
      );


  const contextDescriptors =
    prependMonthlyCarryContextDescriptors_(
      ss,
      descriptors
    );


  const contextAnalyses =
    collectMonthlyAnalysesFromDescriptors_(
      ss,
      contextDescriptors,
      writeStatuses
    );


  const reportingAnalyses =
    contextAnalyses.filter(
      function(info) {
        return info.year === year;
      }
    );


  reportingAnalyses.carryContextAnalyses =
    contextAnalyses;


  reportingAnalyses.groupInventoryAuditContext =
    contextAnalyses.groupInventoryAuditContext;


  return reportingAnalyses;
}


/*
 * 자동 생성 탭은 구분 합계 실사보정 오프셋을 상세행 D열에 배분하지 않는다.
 * 연도가 바뀌어도 오프셋이 끊기지 않도록 현재 연도의 첫 월 앞에서부터
 * 직전 수동 월(새 실측 기준점)까지의 연속 월을 계산 문맥에만 포함한다.
 */
function prependMonthlyCarryContextDescriptors_(
  ss,
  reportingDescriptors
) {

  const current =
    (reportingDescriptors || [])
      .slice()
      .sort(
        function(a, b) {
          return (
            a.year - b.year ||
            a.month - b.month
          );
        }
      );


  if (!current.length) {
    return current;
  }


  const all =
    listMonthlySheetDescriptors_(
      ss
    );


  const byKey =
    new Map();


  all.forEach(
    function(item) {
      byKey.set(
        item.year * 12 +
        item.month - 1,
        item
      );
    }
  );


  const first =
    current[0];


  let cursor =
    first.year * 12 +
    first.month - 2;


  const prefix = [];


  while (byKey.has(cursor)) {

    const item =
      byKey.get(cursor);


    prefix.unshift(
      item
    );


    if (
      !isAutoGeneratedMonthlySheet_(
        item.sheet,
        item.year,
        item.month
      )
    ) {
      break;
    }


    cursor -= 1;
  }


  return prefix.concat(
    current
  );
}


function collectMonthlyAnalysesThrough_(
  ss,
  throughYear,
  throughMonth
) {

  const limit =
    Number(throughYear) * 100 +
    Number(throughMonth);


  const descriptors =
    listMonthlySheetDescriptors_(
      ss
    )
      .filter(
        function(item) {
          return (
            item.year * 100 +
            item.month <=
            limit
          );
        }
      );


  return collectMonthlyAnalysesFromDescriptors_(
    ss,
    descriptors,
    true
  );
}


function collectMonthlyAnalysesFromDescriptors_(
  ss,
  descriptors,
  writeStatuses
) {

  const analyses =
    (descriptors || [])
      .slice()
      .sort(
        function(a, b) {
          return (
            a.year - b.year ||
            a.month - b.month
          );
        }
      )
      .map(
        function(item) {
          return analyzeMonthlySheet_(
            item.sheet,
            item.sheetName,
            item.month,
            item.year
          );
        }
      );


  const groupAuditContext =
    readGroupInventoryAuditRecords_(ss);


  matchGroupInventoryAuditsToBlocks_(
    analyses,
    groupAuditContext.records
  );

  applyInventoryAuditAdjustments_(analyses);
  applyGroupInventoryAuditAdjustments_(
    analyses,
    groupAuditContext.records
  );


  if (writeStatuses) {
    writeGroupInventoryAuditStatuses_(
      groupAuditContext
    );
  }


  analyses.groupInventoryAuditContext =
    groupAuditContext;


  return analyses;
}