


/*
 * 월 1일 설치형 시간 트리거용 함수.
 * 이미 같은 이름의 월 시트가 있으면 중복 생성 없이 종료한다.
 */
function createCurrentMonthSheetOnFirstDay() {

  const now =
    new Date();


  const timeZone =
    MONTHLY_SHEET_CREATION_CONFIG
      .OPERATION_TIME_ZONE;


  const year =
    Number(
      Utilities.formatDate(
        now,
        timeZone,
        "yyyy"
      )
    );


  const month =
    Number(
      Utilities.formatDate(
        now,
        timeZone,
        "M"
      )
    );


  try {

    const result =
      createMonthlySheetForTarget_(
        year,
        month
      );


    Logger.log(
      result.message
    );

  } catch (error) {

    Logger.log(
      "=== 월 작업일지 자동생성 중단 ===\n" +
      error.message
    );

    throw error;
  }
}


function createMonthlySheetForTarget_(
  year,
  month
) {

  return withDocumentLock_(
    "신규 월 작업일지 생성",
    function() {
      return createMonthlySheetForTargetUnlocked_(
        year,
        month
      );
    }
  );
}


function createMonthlySheetForTargetUnlocked_(
  year,
  month
) {

  validateMonthlySheetTarget_(
    year,
    month
  );


  const ss =
    SpreadsheetApp.getActiveSpreadsheet();


  const targetSheetName =
    getMonthlySheetName_(
      year,
      month
    );


  const existing =
    ss.getSheetByName(
      targetSheetName
    );


  if (existing) {

    return {
      created:
        false,

      sheet:
        existing,

      message:
        targetSheetName +
        " 시트가 이미 있으므로 새로 만들지 않았습니다."
    };
  }


  const previous =
    getPreviousMonthTarget_(
      year,
      month
    );


  const previousSheetName =
    getMonthlySheetName_(
      previous.year,
      previous.month
    );


  const previousSheet =
    ss.getSheetByName(
      previousSheetName
    );


  if (!previousSheet) {

    throw new Error(
      "전월 원본 시트가 없습니다: " +
      previousSheetName +
      "\n전월 시트를 먼저 확인한 뒤 다시 실행하세요."
    );
  }


  const monthlyAnalyses =
    collectMonthlyAnalysesThrough_(
      ss,
      previous.year,
      previous.month
    );


  const previousInfo =
    findMonthlyAnalysisBySheetName_(
      monthlyAnalyses,
      previousSheetName
    );


  if (
    !previousInfo ||
    !previousInfo.hasValidInput ||
    !previousInfo.validBlocks.length
  ) {

    throw new Error(
      previousSheetName +
      "에 유효 작업일지가 없어 최종재고를 안전하게 이월할 수 없습니다."
    );
  }


  const closingInventory =
    buildAdjustedClosingInventoryMap_(
      previousInfo
    );


  if (!closingInventory.size) {

    throw new Error(
      previousSheetName +
      "에서 이월 가능한 상세 최종재고를 찾지 못했습니다."
    );
  }


  const templateSheet =
    ensureMonthlyDiaryTemplate_(
      ss,
      previousSheet
    );


  let targetSheet =
    null;


  try {

    targetSheet =
      templateSheet.copyTo(
        ss
      );


  targetSheet
    .setName(
      targetSheetName
    )
    .showSheet();


  markAutoGeneratedMonthlySheet_(
    targetSheet,
    year,
    month
  );


  Logger.log(
    "신규 월 시트 복제 완료: " +
    targetSheetName
  );


  const copiedBlocks =
    collectAllDateBlocks_(
      targetSheet
    );


  if (!copiedBlocks.length) {

    throw new Error(
      "자동생성 템플릿에서 날짜 블록을 찾지 못했습니다. 템플릿 구조를 확인하세요."
    );
  }


  clearManualMonthlyEntries_(
    targetSheet,
    copiedBlocks
  );


  updateMonthlyDateCells_(
    targetSheet,
    copiedBlocks,
    year,
    month
  );


  SpreadsheetApp.flush();


  Logger.log(
    "신규 월 날짜 갱신 완료: " +
    targetSheetName
  );


  const targetInfo =
    analyzeMonthlySheet_(
      targetSheet,
      targetSheetName,
      month,
      year
    );


  const expectedCalendarDays =
    new Date(
      year,
      month,
      0
    ).getDate();


  if (
    targetInfo.allBlocks.length !==
    expectedCalendarDays
  ) {
    throw new Error(
      "새 월 날짜 블록 수가 올바르지 않습니다. 기대 " +
      expectedCalendarDays +
      "일 / 확인 " +
      targetInfo.allBlocks.length +
      "일"
    );
  }


  const firstBlock =
    findFirstCalendarDayBlock_(
      targetInfo.allBlocks
    );


  if (!firstBlock) {

    throw new Error(
      "새 월 시트에서 " +
      year + "." + month + ".01 날짜 블록을 찾지 못했습니다."
    );
  }


  const carryResult =
    carryClosingInventoryToFirstDay_(
      targetSheet,
      targetInfo.scan,
      firstBlock,
      closingInventory
    );


  if (
    !carryResult.carriedCount ||
    carryResult.missingKeys.length ||
    carryResult.unusedKeys.length
  ) {

    throw new Error(
      "전월 최종재고와 새 월 1일 돈사·돈방 구조가 완전히 일치하지 않습니다.\n" +
      "이월: " + carryResult.carriedCount +
      ", 새 월 미일치: " + carryResult.missingKeys.length +
      ", 전월 미사용: " + carryResult.unusedKeys.length
    );
  }


  Logger.log(
    "신규 월 이월재고 적용 완료: " +
    carryResult.carriedCount +
    "개 상세행"
  );


  configureInventoryAuditInputForMonthlySheet_(
      targetSheet,
      targetSheetName,
      month,
      year
    );


  Logger.log(
    "신규 월 J열 실사입력 설정 완료: " +
    targetSheetName
  );


  refreshDashboardLinksUnlocked_();


  Logger.log(
    [
      "=== 신규 월 작업일지 생성 완료 ===",
      "생성 시트: " + targetSheetName,
      "템플릿: " + templateSheet.getName(),
      "전월: " + previousSheetName,
      "실사보정 후 이월 재고행: " + carryResult.carriedCount,
      "대시보드 연동: 갱신 완료"
    ].join("\n")
  );


  return {
    created:
      true,

    sheet:
      targetSheet,

    message:
      targetSheetName +
      " 시트를 생성했습니다.\n" +
      "전월 실사보정 후 최종재고 " +
      carryResult.carriedCount +
      "개 상세행을 1일 전일재고로 이월했고, 대시보드 연동도 갱신했습니다."
  };

  } catch (error) {

    if (
      targetSheet &&
      ss.getSheetByName(
        targetSheetName
      ) === targetSheet
    ) {

      ss.deleteSheet(
        targetSheet
      );
    }


    throw new Error(
      error.message +
      "\n생성 중이던 " +
      targetSheetName +
      " 시트는 자동으로 제거했습니다."
    );
  }
}