


function auditMonthlyCarryovers_(analyses) {

  const ordered =
    (analyses || [])
      .slice()
      .sort(
        function(a, b) {
          return (
            a.year - b.year ||
            a.monthIndex - b.monthIndex
          );
        }
      );


  const issues = [];


  for (
    let index = 1;
    index < ordered.length;
    index++
  ) {

    const previous =
      ordered[index - 1];

    const current =
      ordered[index];


    const previousKey =
      previous.year * 12 +
      previous.monthIndex;

    const currentKey =
      current.year * 12 +
      current.monthIndex;


    if (currentKey - previousKey !== 1) {
      continue;
    }


    const previousBlock =
      (previous.validBlocks || []).slice(-1)[0] ||
      (previous.allBlocks || []).slice(-1)[0] ||
      null;

    const currentBlock =
      (current.allBlocks || [])[0] ||
      null;


    const closing =
      getGrandTotalStockFromBlock_(
        current.autoGenerated
          ? (
              previous.adjustedScan ||
              previous.scan
            )
          : previous.scan,
        previousBlock,
        8
      );

    const opening =
      getGrandTotalStockFromBlock_(
        current.scan,
        currentBlock,
        3
      );


    if (
      closing === null ||
      opening === null ||
      closing === opening
    ) {
      continue;
    }


    issues.push({
      previousSheetName: previous.sheetName,
      currentSheetName: current.sheetName,
      closing: closing,
      opening: opening,
      difference: opening - closing,
      autoGenerated: Boolean(current.autoGenerated)
    });
  }


  const lines =
    issues.map(
      function(item) {
        return (
          item.previousSheetName +
          " 최종 " +
          item.closing +
          " → " +
          item.currentSheetName +
          " 최초 " +
          item.opening +
          " (차이 " +
          item.difference +
          ")" +
          (
            item.autoGenerated
              ? " [자동생성 탭 오류]"
              : " [원본 수기 이월 차이: 공식 통계는 관리사무소 기준 유지]"
          )
        );
      }
    );


  return {
    issues: issues,
    message: issues.length
      ? "=== 월 경계 이월재고 불일치 ===\n" +
        lines.join("\n")
      : "월 경계 이월재고 불일치 없음"
  };
}