


/***************************************************************
 * 최신 유효 월
 ***************************************************************/

function findLatestMonthlySheetWithValidData_(
  monthlyAnalyses
) {

  const candidates =
    (monthlyAnalyses || [])
      .filter(
        function(info) {

          return (
            info &&
            info.hasValidInput
          );
        }
      );


  if (!candidates.length) {
    return null;
  }


  candidates.sort(
    function(a, b) {

      return (
        a.monthIndex -
        b.monthIndex
      );
    }
  );


  return candidates[
    candidates.length - 1
  ];
}


/***************************************************************
 * 월 작업일지 분석
 *
 * 날짜행
 *   ↓
 * 다음 날짜행 직전
 *   ↓
 * A열 앵커 검색
 *   ↓
 * 같은 행 E:H 직접입력 검사
 *
 ***************************************************************/

function analyzeMonthlySheet_(
  sheet,
  sheetName,
  monthIndex,
  reportingYear
) {

  const year =
    Number(
      reportingYear ||
      getDashboardReportingYear_()
    );

  const scan =
    scanMonthlySheet_(
      sheet
    );


  const dateRows =
    collectDateRowsForMonth_(
      scan,
      monthIndex,
      year
    );


  if (!dateRows.length) {

    return createEmptyMonthlyAnalysis_(
      sheet,
      sheetName,
      monthIndex,
      year,
      scan
    );
  }


  const validBlocks = [];

  const allBlocks = [];


  for (
    let i = 0;
    i < dateRows.length;
    i++
  ) {

    const current =
      dateRows[i];


    const nextDateRow =
      current.nextDateRow;


    const blockEndRow =
      nextDateRow
        ? nextDateRow - 1
        : scan.lastRow;


    const validation =
      inspectAnchorInputsInBlock_(
        scan,
        current.row,
        blockEndRow
      );


    const inventoryAudit =
      inspectInventoryAuditInputsInBlock_(
        scan,
        current.row,
        blockEndRow
      );


    const block = {

      date:
        current.date,

      dateBlockStartRow:
        current.row,

      nextDateRow:
        nextDateRow,

      copyEndRow:
        blockEndRow,

      matchedAnchorCount:
        validation.matchedAnchorCount,

      inputAnchorCount:
        validation.inputAnchorCount,

      matchedAnchors:
        validation.matchedAnchors,

      inputAnchors:
        validation.inputAnchors,

      missingAnchors:
        validation.missingAnchors,

      inventoryAuditCount:
        inventoryAudit.count,

      inventoryAuditCells:
        inventoryAudit.cells,

      hasValidInput:
        (
          validation.hasValidInput ||
          inventoryAudit.count > 0
        )
    };


    allBlocks.push(
      block
    );


    if (
      block.hasValidInput
    ) {

      validBlocks.push(
        block
      );
    }
  }


  if (!validBlocks.length) {

    const empty =
      createEmptyMonthlyAnalysis_(
        sheet,
        sheetName,
        monthIndex,
        year,
        scan
      );


    empty.allBlocks =
      allBlocks;


    return empty;
  }


  validBlocks.sort(
    function(a, b) {

      return (
        a.date.getTime() -
        b.date.getTime()
      );
    }
  );


  const latest =
    validBlocks[
      validBlocks.length - 1
    ];


  return {

    sheet:
      sheet,

    sheetName:
      sheetName,

    monthIndex:
      monthIndex,

    year:
      year,

    autoGenerated:
      isAutoGeneratedMonthlySheet_(
        sheet,
        year,
        monthIndex
      ),

    scan:
      scan,

    hasValidInput:
      true,

    validCount:
      validBlocks.length,

    validBlocks:
      validBlocks,

    allBlocks:
      allBlocks,

    dateBlockStartRow:
      latest.dateBlockStartRow,

    nextDateRow:
      latest.nextDateRow,

    copyEndRow:
      latest.copyEndRow,

    latestDate:
      latest.date,

    matchedAnchorCount:
      latest.matchedAnchorCount,

    inputAnchorCount:
      latest.inputAnchorCount,

    missingAnchors:
      latest.missingAnchors,

    inventoryAuditCount:
      validBlocks.reduce(
        function(sum, block) {
          return (
            sum +
            Number(
              block.inventoryAuditCount || 0
            )
          );
        },
        0
      )
  };
}


/***************************************************************
 * 빈 월 분석 객체
 ***************************************************************/

function createEmptyMonthlyAnalysis_(
  sheet,
  sheetName,
  monthIndex,
  reportingYear,
  scan
) {

  return {

    sheet:
      sheet,

    sheetName:
      sheetName,

    monthIndex:
      monthIndex,

    year:
      Number(reportingYear),

    autoGenerated:
      isAutoGeneratedMonthlySheet_(
        sheet,
        Number(reportingYear),
        monthIndex
      ),

    scan:
      scan,

    hasValidInput:
      false,

    validCount:
      0,

    validBlocks:
      [],

    allBlocks:
      [],

    dateBlockStartRow:
      "",

    nextDateRow:
      "",

    copyEndRow:
      0,

    latestDate:
      null,

    matchedAnchorCount:
      0,

    inputAnchorCount:
      0,

    missingAnchors:
      [],

    inventoryAuditCount:
      0,

    groupInventoryAuditCount:
      0,

    outputValues:
      [],

    reportingOutputValues:
      []
  };
}


/***************************************************************
 * 해당 월 날짜행 수집
 ***************************************************************/

function collectDateRowsForMonth_(
  scan,
  monthIndex,
  reportingYear
) {

  const result = [];

  const allDateRows = [];

  const seenDateKeys =
    new Set();


  for (
    let rowNum = 1;
    rowNum <= scan.lastRow;
    rowNum++
  ) {

    const date =
      getDateFromRow_(
        scan.values[
          rowNum - 1
        ],
        scan.displayValues[
          rowNum - 1
        ]
      );


    if (!date) {
      continue;
    }


    const item = {

      row:
        rowNum,

      date:
        new Date(
          date.getFullYear(),
          date.getMonth(),
          date.getDate()
        ),

      nextDateRow:
        null
    };


    if (allDateRows.length) {

      allDateRows[
        allDateRows.length - 1
      ].nextDateRow =
        rowNum;
    }


    allDateRows.push(
      item
    );


    if (
      date.getFullYear() !==
        Number(reportingYear) ||
      date.getMonth() + 1 !==
        monthIndex
    ) {

      continue;
    }


    /*
     * 같은 날짜가 여러 행에서 발견될 경우
     * 최초 날짜행만 사용한다.
     *
     * nextDateRow는 월/연도와 무관한 바로 다음 날짜행이다.
     * 기존 findNextDateRowAfter_()의 경계 판정을 그대로 보존한다.
     */
    const key =
      dateKey_(
        item.date
      );


    if (
      !seenDateKeys.has(
        key
      )
    ) {

      seenDateKeys.add(
        key
      );

      result.push(
        item
      );
    }
  }


  if (
    allDateRows.length &&
    !allDateRows[
      allDateRows.length - 1
    ].nextDateRow
  ) {

    const trailingBoundaryRow =
      findTrailingUndatedTemplateBoundaryRow_(
        scan,
        allDateRows[
          allDateRows.length - 1
        ].row
      );


    if (trailingBoundaryRow) {
      allDateRows[
        allDateRows.length - 1
      ].nextDateRow =
        trailingBoundaryRow;
    }
  }


  return result;
}


/*
 * 실제 작업일지에는 31일 뒤에 날짜 셀만 빈 예비 작업 블록이 있다.
 * 날짜가 없더라도 바로 다음 행이 월 작업일지 열 제목이면 그 빈 날짜행을
 * 마지막 실제 날짜 블록의 경계로 사용해 월말 재고가 중복 집계되지 않게 한다.
 */
function findTrailingUndatedTemplateBoundaryRow_(
  scan,
  afterRow
) {

  if (!scan) {
    return null;
  }


  for (
    let rowNum = Number(afterRow || 0) + 1;
    rowNum < scan.lastRow;
    rowNum++
  ) {

    const valueRow =
      scan.values[rowNum - 1];


    const displayRow =
      scan.displayValues[rowNum - 1];


    const formulaRow =
      scan.formulas[rowNum - 1];


    const boundaryRowIsBlank =
      Array.from({
        length:
          DASHBOARD_CONFIG.SOURCE_DATA_COLS
      }).every(
        function(_, col) {
          return (
            cellText_(
              displayRow,
              valueRow,
              col
            ) === "" &&
            String(
              formulaRow &&
              formulaRow[col] ||
              ""
            ).trim() === ""
          );
        }
      );


    if (!boundaryRowIsBlank) {
      continue;
    }


    const nextValueRow =
      scan.values[rowNum];


    const nextDisplayRow =
      scan.displayValues[rowNum];


    if (
      normalizeText_(
        cellText_(
          nextDisplayRow,
          nextValueRow,
          0
        )
      ) === "отделение" &&
      normalizeText_(
        cellText_(
          nextDisplayRow,
          nextValueRow,
          3
        )
      ) === "предыдущий день" &&
      normalizeText_(
        cellText_(
          nextDisplayRow,
          nextValueRow,
          8
        )
      ) === "текущий день"
    ) {
      return rowNum;
    }
  }


  return null;
}


/***************************************************************
 * 작업일 블록의 앵커 및 E:H 검사
 ***************************************************************/

function inspectAnchorInputsInBlock_(
  scan,
  startRow,
  endRow
) {

  const anchorMap =
    new Map();


  DASHBOARD_CONFIG.INPUT_ANCHORS
    .forEach(
      function(anchor) {

        anchorMap.set(
          anchor.key,
          {

            config:
              anchor,

            found:
              false,

            row:
              null,

            hasManualInput:
              false,

            inputCells:
              []
          }
        );
      }
    );


  /*
   * 작업일 블록 내부 A열 검색
   */
  for (
    let rowNum = startRow;
    rowNum <= endRow;
    rowNum++
  ) {

    const displayRow =
      scan.displayValues[
        rowNum - 1
      ];


    const formulaRow =
      scan.formulas[
        rowNum - 1
      ];


    if (
      !displayRow ||
      !formulaRow
    ) {

      continue;
    }


    /*
     * A열 제목
     */
    const colAText =
      normalizeAnchorText_(
        displayRow[0]
      );


    if (!colAText) {
      continue;
    }


    const anchor =
      findMatchingInputAnchor_(
        colAText
      );


    if (!anchor) {
      continue;
    }


    const state =
      anchorMap.get(
        anchor.key
      );


    /*
     * 같은 날짜 블록 안에
     * 동일 앵커가 여러 번 있어도
     * 최초 일치행을 기준으로 한다.
     */
    if (state.found) {
      continue;
    }


    state.found =
      true;


    state.row =
      rowNum;


    /*
     * =========================================================
     * E:H 직접입력 검사
     *
     * D열은 검사하지 않는다.
     * =========================================================
     */

    for (
      let colNum =
        DASHBOARD_CONFIG.VALIDATION_FIRST_COL;

      colNum <=
        DASHBOARD_CONFIG.VALIDATION_LAST_COL;

      colNum++
    ) {

      const displayValue =
        displayRow[
          colNum - 1
        ];


      const formula =
        formulaRow[
          colNum - 1
        ];


      if (
        isManualNumericInput_(
          displayValue,
          formula
        )
      ) {

        state.hasManualInput =
          true;


        state.inputCells.push(
          columnNumberToLetter_(
            colNum
          ) +
          rowNum
        );
      }
    }
  }


  const matchedAnchors = [];

  const inputAnchors = [];

  const missingAnchors = [];


  anchorMap.forEach(
    function(state) {

      if (
        state.found
      ) {

        matchedAnchors.push({

          key:
            state.config.key,

          title:
            state.config.canonical,

          row:
            state.row,

          hasManualInput:
            state.hasManualInput,

          inputCells:
            state.inputCells.slice()
        });


        if (
          state.hasManualInput
        ) {

          inputAnchors.push({

            key:
              state.config.key,

            title:
              state.config.canonical,

            row:
              state.row,

            inputCells:
              state.inputCells.slice()
          });
        }

      } else {

        missingAnchors.push(
          state.config.canonical
        );
      }
    }
  );


  return {

    /*
     * 네 앵커 중 한 곳이라도
     * E:H 직접입력이 있으면 유효 작업일
     */
    hasValidInput:
      inputAnchors.length > 0,

    matchedAnchorCount:
      matchedAnchors.length,

    inputAnchorCount:
      inputAnchors.length,

    matchedAnchors:
      matchedAnchors,

    inputAnchors:
      inputAnchors,

    missingAnchors:
      missingAnchors
  };
}


/***************************************************************
 * 앵커 검색
 ***************************************************************/

function findMatchingInputAnchor_(
  normalizedValue
) {

  for (
    let i = 0;
    i <
      DASHBOARD_CONFIG.INPUT_ANCHORS.length;
    i++
  ) {

    const anchor =
      DASHBOARD_CONFIG.INPUT_ANCHORS[i];


    for (
      let j = 0;
      j < anchor.aliases.length;
      j++
    ) {

      if (
        normalizedValue ===
        normalizeAnchorText_(
          anchor.aliases[j]
        )
      ) {

        return anchor;
      }
    }
  }


  return null;
}


/***************************************************************
 * 앵커 문자열 정규화
 ***************************************************************/

function normalizeAnchorText_(value) {

  return String(
    value == null
      ? ""
      : value
  )
    .replace(
      /\u00A0/g,
      " "
    )
    .replace(
      /\s+/g,
      " "
    )
    .trim()
    .toLocaleLowerCase(
      "ru-RU"
    );
}


/***************************************************************
 * E:H 직접입력 숫자 판정
 ***************************************************************/

function isManualNumericInput_(
  displayValue,
  formula
) {

  /*
   * 수식 셀 제외
   */
  if (
    String(
      formula == null
        ? ""
        : formula
    ).trim() !== ""
  ) {

    return false;
  }


  const text =
    String(
      displayValue == null
        ? ""
        : displayValue
    )
      .replace(
        /\u00A0/g,
        ""
      )
      .replace(
        /\s/g,
        ""
      )
      .trim();


  if (!text) {
    return false;
  }


  const normalized =
    text.replace(
      /,/g,
      "."
    );


  if (
    !/^-?\d+(\.\d+)?$/
      .test(
        normalized
      )
  ) {

    return false;
  }


  const n =
    Number(
      normalized
    );


  if (
    !Number.isFinite(
      n
    )
  ) {

    return false;
  }


  if (
    n === 0 &&
    !DASHBOARD_CONFIG
      .COUNT_ZERO_AS_VALID_INPUT
  ) {

    return false;
  }


  return true;
}


function collectAllDateBlocks_(sheet) {

  const scan =
    scanMonthlySheet_(
      sheet
    );


  const dateRows = [];


  for (
    let rowNum = 1;
    rowNum <= scan.lastRow;
    rowNum++
  ) {

    const date =
      getDateFromRow_(
        scan.values[rowNum - 1],
        scan.displayValues[rowNum - 1]
      );


    if (!date) {
      continue;
    }


    dateRows.push({
      date:
        date,

      dateBlockStartRow:
        rowNum,

      nextDateRow:
        null,

      copyEndRow:
        scan.lastRow
    });
  }


  dateRows.forEach(
    function(block, index) {

      const next =
        dateRows[index + 1];


      if (next) {

        block.nextDateRow =
          next.dateBlockStartRow;

        block.copyEndRow =
          next.dateBlockStartRow - 1;
      }
    }
  );


  if (dateRows.length) {

    const lastBlock =
      dateRows[
        dateRows.length - 1
      ];


    const trailingBoundaryRow =
      findTrailingUndatedTemplateBoundaryRow_(
        scan,
        lastBlock.dateBlockStartRow
      );


    if (trailingBoundaryRow) {
      lastBlock.nextDateRow =
        trailingBoundaryRow;

      lastBlock.copyEndRow =
        trailingBoundaryRow - 1;
    }
  }


  return dateRows;
}


function findFirstCalendarDayBlock_(blocks) {

  return (blocks || [])
    .filter(
      function(block) {

        return (
          block &&
          block.date &&
          block.date.getDate() === 1
        );
      }
    )
    .sort(
      function(a, b) {

        return (
          a.dateBlockStartRow -
          b.dateBlockStartRow
        );
      }
    )[0] || null;
}


function findMonthlyAnalysisBySheetName_(
  analyses,
  sheetName
) {

  return (analyses || [])
    .filter(
      function(info) {

        return (
          info &&
          info.sheetName === sheetName
        );
      }
    )[0] || null;
}